version: "3.7"

services:
  todo:
    build: .\app
    ports:
      - 3000:3000
    networks: 
      - todo-app
  mysql:
    image: mysql:8.0
    networks: 
      - todo-app
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
  
networks:
  todo-app:

volumes:
  todo-mysql-data: